### ISSUE TITLE
Media which is updated is being blocked from google

### ISSUE THREAD

**Issue by quisse** [FriendsOfShopware/FroshRobotsTxt#7]
### Shopware Version

6.6.5.1

### Plugin Version

0.2.0

### Actual behaviour

image.webp?ts=1719237274 should be indexed by google

### Expected behaviour

image.webp?ts=1719237274 is blocked by `/*?` from google

### Steps to Reproduce?

When media is changed, [Shopware will append a querystring to bust caches](https://github.com/shopware/shopware/blob/trunk/src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php#L28-L30). This makes that google cannot index the updated image url.
Adding `Allow: /*?ts` will overcome this issue.

**Comment by aragon999** [comment]
Can you check if version 0.2.1 solves the issue? In there we whitelisted the files `Allow: /media/*?ts=`: https://github.com/FriendsOfShopware/FroshRobotsTxt/commit/52afcc9a08396be9d1172321d6f1f366de604de7

**Comment by quisse** [comment]
Ooh ok, I didn't saw it in the readme

**Comment by quisse** [comment]
updated readme in https://github.com/FriendsOfShopware/FroshRobotsTxt/pull/8
